services:
  pedo-connecter:
    build: ../PedoConnector
    container_name: pedo-connecter
    ports:
      - "9341:9341"
    volumes:
      - ../PedoConnector/src:/app/src
    command: ["fastapi", "run", "/app/src/main.py", "--port", "9341", "--reload"]
  pedo-hunter-api:
    build:
      context: ../PedoHunter
      dockerfile: Dockerfile.api  
    container_name: pedo-hunter-api
    ports:
      - "6969:80"
    environment:
      - OLLAMA_HOST=http://pedo-hunter-ollama:11434  # Points to the ollama service for chat
    depends_on:
      - pedo-hunter-ollama
    networks:
      - pedo-hunter-network
  pedo-hunter-ollama:
    build:
      context: ../PedoHunter
      dockerfile: Dockerfile.ai
    container_name: pedo-hunter-ai
    # For NVIDIA GPUs, use this :
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    ports:
      - "11469:11434"
    volumes:
      - ollama_data:/root/.ollama  # Persist Ollama models
    networks:
      - pedo-hunter-network

networks:
  pedo-hunter-network:
    driver: bridge

volumes:
  ollama_data:
